from helpers_and_functions.constants_files.constants_menu import WIDTH,HEIGHT

REFRESH_RATE = 10000
BACKGROUND_COLOR = (0, 128, 255)
START_BUTTON_X = round(WIDTH / 2)
START_BUTTON_Y = round(HEIGHT / 2)
START_BUTTON_WIDTH = round(WIDTH / 5)
START_BUTTON_HEIGHT = round(HEIGHT / 5)

START_NEW_ROUND_X = round(WIDTH * 7 / 10)
START_NEW_ROUND_Y = round(HEIGHT * 7 / 10)
START_NEW_ROUND_WIDTH = round(WIDTH / 7)
START_NEW_ROUND_HEIGHT = round(HEIGHT / 7)

CUP_WIDTH = round(WIDTH / 6)
CUP_HEIGHT = round(HEIGHT * 1.5 / 6)
CUP_Y = round(HEIGHT / 6)
DOWN_CUP_HEIGHT = round(HEIGHT * 3 / 6)
FIRST_CUP_START_X = round(WIDTH / 6)
SECOND_CUP_START_X = round(WIDTH * 2 / 6)
THIRD_CUP_START_X = round(WIDTH * 3 / 6)

BALL_WIDTH = round(CUP_WIDTH / 3)
BALL_HEIGHT = round(CUP_HEIGHT*2 / 3)
FIRST_CUP_BALL_X = FIRST_CUP_START_X + round(FIRST_CUP_START_X / 4)
SECOND_CUP_BALL_X = FIRST_CUP_BALL_X + round(WIDTH / 6)
THIRD_CUP_BALL_X = SECOND_CUP_BALL_X + round(WIDTH / 6)
BALL_Y = DOWN_CUP_HEIGHT + round(CUP_HEIGHT / 3)


FEEDBACK_X = WIDTH - round(WIDTH/5)
FEEDBACK_Y = round(HEIGHT/7)
FEEDBACK_WIDTH = round(WIDTH/6)
FEEDBACK_HEIGHT = round(HEIGHT/3.5)