from helpers_and_functions.constants_files.constants_menu import WIDTH, HEIGHT

HOST_HEIGHT_LOC = round(HEIGHT/5)
HOST_WIDTH_LOC = round(WIDTH/2.8)
HOST_HEIGHT = round(HEIGHT/4)
HOST_WIDTH = round(WIDTH/4)


QUESTION_BLOCK_HEIGHT = round(HEIGHT / 2.66)
QUESTION_BLOCK_WIDTH = round(WIDTH / 1.42)

HELP_BUTTON_HEIGHT = round(HEIGHT / 10)
HELP_BUTTON_WIDTH = round(WIDTH / 10)

FIFTY_BUTTON_HEIGHT_LOC = HEIGHT - QUESTION_BLOCK_HEIGHT - HELP_BUTTON_HEIGHT - round(HEIGHT / 40)
FIFTY_BUTTON_WIDTH_LOC = WIDTH / 2 - HELP_BUTTON_WIDTH - round(WIDTH / 50)

SWITCH_BUTTON_HEIGHT_LOC = HEIGHT - QUESTION_BLOCK_HEIGHT - HELP_BUTTON_HEIGHT - round(HEIGHT / 40)
SWITCH_BUTTON_WIDTH_LOC = WIDTH / 2 + round(WIDTH / 50)

QUESTION_LOCATION_HEIGHT = HEIGHT / 2 + round(HEIGHT / 4)
QUESTION_LOCATION_WIDTH = WIDTH / 2

ANSWER1_LOCATION_HEIGHT = HEIGHT / 2 + round(HEIGHT / 2.9)
ANSWER1_LOCATION_WIDTH = WIDTH / 2 - round(WIDTH / 6.45)

ANSWER2_LOCATION_HEIGHT = HEIGHT / 2 + round(HEIGHT / 2.9)
ANSWER2_LOCATION_WIDTH = WIDTH / 2 + round(WIDTH / 6.45)

ANSWER3_LOCATION_HEIGHT = HEIGHT / 2 + round(HEIGHT / 2.35)
ANSWER3_LOCATION_WIDTH = WIDTH / 2 - round(WIDTH / 6.45)

ANSWER4_LOCATION_HEIGHT = HEIGHT / 2 + round(HEIGHT / 2.35)
ANSWER4_LOCATION_WIDTH = WIDTH / 2 + round(WIDTH / 6.45)

ANSWER_BOX_SIZE_HEIGHT = round(HEIGHT / 16)
ANSWER_BOX_SIZE_WIDTH = round(WIDTH / 3.5)

BOX_MARGIN_HEIGHT = -round(HEIGHT / 33.8)
BOX_MARGIN_WIDTH = -round(WIDTH / 6.8)

BLUE = (100, 106, 205)
PINK = (184, 61, 186)

LEFT = 1
REFRESH_RATE = 5
